# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macos-latest

steps:

- task: CmdLine@2
  inputs:
    script: 'git submodule update --init --recursive'
- task: CmdLine@2
  inputs:
    script: 'mkdir build && cd build'
- task: CMake@1
  inputs:
    cmakeArgs: -S ..

- task: CmdLine@2
  inputs:
    script: 'sudo make -j 4 -v'
